// This file defines boilerplate code that forms part of every
// generated Go file.

package main

// header is included at the top of every generated Go file.
var header = `// This file was generated by gosp2go.

package main

import "gosp"
`

// body begins the function that was converted from a Go Server Page to Go.
var bodyBegin = `// GospGeneratePage represents the user's Go Server page, converted to Go.
func GospGeneratePage(gospReq *gosp.RequestData, gospOut gosp.Writer, gospMeta gosp.Metadata) {
	// On exit, close the metadata channel.  If the user's code panicked,
	// change the return code to "internal server error".
	defer func() {
		r := recover()
		if r != nil {
			gosp.ReportPanic(r, gospMeta)
		}
		close(gospMeta)
	}()

	// Express the Gosp page in Go.
`
