#! /usr/bin/env perl

###########################################
# Extract the RequestData struct from     #
# gosp.go and paste it into predefined.md #
#                                         #
# By Scott Pakin <scott+gosp@pakin.org>   #
###########################################

# Usage
# -----
#
# Add the following to .git/hooks/pre-commit:
#
#   ./git-scripts/extract-requestdata 
#   git add docs/predefined.md

use warnings;
use strict;

# Read the RequestData definition from gosp.go.
undef $/;
open(GOSP, "<", "src/gosp/gosp.go") || die $!;
my $gosp = <GOSP>;
close GOSP or die;
die if $gosp !~ m,^type RequestData struct.*?^\},ms;
my $reqdata_new = $&;

# Replace the RequestData definition in predefined.md.
open(PREDEF, "<", "docs/predefined.md") || die $!;
my $predef = <PREDEF>;
close PREDEF or die;
die if $predef !~ m,^type RequestData struct.*?^\},ms;
my $reqdata_old = $&;
$predef =~ s/\Q$reqdata_old\E/$reqdata_new/ms;
open(PREDEF, ">", "docs/predefined.md") || die $!;
print PREDEF $predef;
close PREDEF or die;
