remote_theme: pmarsceill/just-the-docs

title: Go Server Pages

description: Embed Go code within HTML

baseurl: "/"

aux_links:
  "Download <em>Go Server Pages</em> from GitHub":
    - "https://github.com/spakin/gosp"

footer_content: 'Copyright &copy; 2019 <a href="https://www.pakin.org/~scott/">Scott Pakin</a>.<br />
The gopher in the Go Server Pages logo was designed by
<a href="http://reneefrench.blogspot.com/">Renee French</a> and is licensed
under <a href="https://creativecommons.org/licenses/by/3.0/">CC-BY-3.0</a>.'

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

logo: "assets/img/gosp-logo-small.png"
