remote_theme: pmarsceill/just-the-docs

title: Go Server Pages

description: Embed Go code within HTML

aux_links:
  "Download <em>Go Server Pages</em> from GitHub":
    - "//github.com/spakin/gosp"

footer_content: "Copyright &copy; 2019 Scott Pakin"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

logo: "assets/img/gosp-logo-small.png"
